### ISSUE TITLE
Handle all dree options

### ISSUE THREAD

**Issue by euberdeveloper** [jaywcjlove/github-action-folder-tree#2]
Hello, I've noticed this action and I think it's similar (but with different purpose) with this other action: [ga-dree](https://github.com/euberdeveloper/ga-dree).

I would invite you to look at the possible [options](https://github.com/euberdeveloper/ga-dree/blob/main/action.yml) and see if you could add something to your options.

**Comment by jaywcjlove** [comment]
@euberdeveloper  We used a different `tree` package that offers more extensive features. Our usage is focused on outputting `tree` logs, which need to be written into the `README.md` file. We might need an additional action like [`github-action-modify-file-content`](https://github.com/jaywcjlove/github-action-modify-file-content).

**Comment by jaywcjlove** [comment]
@euberdeveloper I think you are promoting your dree, and I think I can switch to it.

**Comment by jaywcjlove** [comment]
I'm already using `dree`. 😄

**Comment by euberdeveloper** [comment]
Yes, I was saying that there can could be further configurations for the action, that could reflect dree's config
